### ISSUE TITLE
Libre.fm register leads to this repo

### ISSUE THREAD

**Issue by httpsterio** [foocorp/hacienda#6]
After trying to sign up for Libre.fm, the Register function leads to this repo. Is it a bug? Is sign ups closed?

**Comment by mattl** [comment]
This is intentional. No more sign ups for now. 

On November 27, 2023, GitHub ***@***.***> wrote:
> After trying to sign up for Libre.fm, the Register function leads to
> this repo. Is it a bug? Is sign ups closed?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/foocorp/hacienda/issues/6>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAIEEFT3RT5F66ILRYTXKTYGSVMNAVCNFSM6AAAAAA74GPDFSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGAYTENJRGE3TIMY>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by mattl** [comment]
See #8
